---
- name: Setup Ubuntu Environment
  hosts: localhost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - debug: var=username_on_the_host.stdout
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install required APT packages
      apt:
        name:
          - apt-transport-https
          - gnupg
          - sudo
          - ca-certificates
          - curl
          - jq
          - zsh
          - guake
          - git
          - make
          - golang-go
          - openjdk-8-jre
          - gpg
        state: present
      register: apt_packages
      retries: 3
      delay: 5
      until: apt_packages is succeeded

    - name: Install Snap packages
      community.general.snap:
        name: '{{ item.name }}'
        classic: '{{ item.classic | default(false) }}'
        state: present
      loop:
        - { name: slack, classic: true }
      register: snap_packages

    - name: Add user to zsh shell if not default
      user:
        name: '{{ username_on_the_host.stdout }}'
        shell: /usr/bin/zsh
      when: ansible_env.SHELL != '/usr/bin/zsh'

    - name: Install Oh My Zsh if not installed
      stat:
        path: '/home/{{ username_on_the_host.stdout }}/.oh-my-zsh'
      register: oh_my_zsh_install

    - name: Copy .zshrc template to user's home directory
      become: false
      template:
        src: templates/.zshrc.j2
        dest: '~/.zshrc'
        mode: '0644'

    - name: Copy .zshrc.aliases template to user's home directory
      become: false
      template:
        src: templates/.zsh_aliases.j2
        dest: '~/.zsh_aliases'
        mode: '0644'

    - name: Install Oh My Zsh
      become: false
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        executable: /bin/bash
      when: not oh_my_zsh_install.stat.exists


    - name: Copy Guake settings template to temporary configuration file
      template:
        src: templates/guake.cfg.j2
        dest: "/tmp/myprefs.cfg"
        mode: '0644'

    - name: Restore Guake preferences from the configuration file
      shell: "guake --restore-preferences=/tmp/myprefs.cfg"
      become: false
      args:
        executable: /bin/bash

    - name: Remove temporary Guake configuration file
      file:
        path: "/tmp/myprefs.cfg"
        state: absent

    - name: Install k9s via Snap (using command module)
      become: true
      command: snap install k9s --devmode
      args:
        creates: /snap/bin/k9s

    - name: Create directory for Docker's GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Print architecture variables
      become: false
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}\n User: {{ username_on_the_host.stdout }}"

    - name: Add Docker’s official GPG key if not already added
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up Docker repository if not already set
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present
        filename: docker

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: '{{ username_on_the_host.stdout }}'
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd:
        name: '{{ item }}'
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service


    # Kubernetes Installation
    - name: Download k8s apt repo key
      become: true
      shell:
        cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
        state: present
        filename: kubernetes

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Clone the k9s repository
      git:
        repo: 'https://github.com/derailed/k9s.git'
        dest: '/usr/local/src/k9s'
        update: yes

    - name: Build k9s from source
      shell: |
        cd /usr/local/src/k9s
        make build
      args:
        chdir: /usr/local/src/k9s
        creates: /usr/local/src/k9s/execs/k9s

    - name: Move k9s executable to /usr/local/bin
      copy:
        src: '/usr/local/src/k9s/execs/k9s'
        dest: '/usr/local/bin/k9s'
        mode: '0755'

    - name: Set the terminal to 256 colors
      lineinfile:
        path: '/etc/profile.d/k9s.sh'
        line: 'export TERM=xterm-256color'
        create: yes

    # Node.js Installation
    - name: Install Node.js LTS via NodeSource script
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install global npm packages
      npm:
        name: '{{ item }}'
        global: yes
        executable: /usr/bin/npm
      loop:
        - n
        - yarn
        - pnpm
        - '@bazel/bazelisk'

    - name: Ensure npm cache directory exists
      file:
        path: /usr/local/n
        state: directory
        owner: '{{ username_on_the_host.stdout }}'
        group: '{{ username_on_the_host.stdout }}'
        mode: '0755'

    - name: Ensure Node.js directories are owned by user
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ username_on_the_host.stdout }}'
        group: '{{ username_on_the_host.stdout }}'
        mode: '0755'
      loop:
        - /usr/local/bin
        - /usr/local/lib
        - /usr/local/include
        - /usr/local/share

    # Terraform Installation
    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp Terraform repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present
        filename: "hashicorp"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present


    # Google Cloud SDK Installation
    - name: Add Google Cloud SDK GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/cloud.google.gpg
        state: present

    - name: Add Google Cloud SDK repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main'
        filename: google-cloud-sdk
        state: present
      notify: Update apt cache

    - name: Install Google Cloud SDK packages
      apt:
        name:
          - google-cloud-cli
          - google-cloud-sdk-gke-gcloud-auth-plugin
        state: present

  handlers:
    - name: Update apt cache
      apt:
        update_cache: yes
